version: '3.3'
services:
  fast-gpt:
    image: c121914yu/fast-gpt:latest
    network_mode: host
    restart: always
    container_name: fast-gpt
    environment:
      # - AXIOS_PROXY_HOST=127.0.0.1
      # - AXIOS_PROXY_PORT=7890
      # - OPENAI_BASE_URL=https://api.openai.com/v1
      # - OPENAI_BASE_URL_AUTH=可选的安全凭证
      - MY_MAIL=xxxx@qq.com
      - MAILE_CODE=xxxx
      - aliAccessKeyId=xxxx
      - aliAccessKeySecret=xxxx
      - aliSignName=xxxxx
      - aliTemplateCode=SMS_xxxx
      - TOKEN_KEY=xxxx
      - queueTask=1
      - parentUrl=https://hostname/api/openapi/startEvents
      - MONGODB_URI=mongodb://username:passsword@0.0.0.0:27017/?authSource=admin
      - MONGODB_NAME=xxx
      - PG_HOST=0.0.0.0
      - PG_PORT=8100
      - PG_USER=xxx
      - PG_PASSWORD=xxx
      - PG_DB_NAME=xxx
      - OPENAIKEY=sk-xxxxx
  nginx:
    image: nginx:alpine3.17
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - /root/fast-gpt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/fast-gpt/nginx/logs:/var/log/nginx
      - /root/fast-gpt/nginx/ssl/docgpt.key:/ssl/docgpt.key
      - /root/fast-gpt/nginx/ssl/docgpt.pem:/ssl/docgpt.pem
  pg:
    image: ankane/pgvector
    container_name: pg
    restart: always
    ports:
      - 8100:5432
    environment:
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=xxx
    volumes:
      - /root/fast-gpt/pg/data:/var/lib/postgresql/data
      - /root/fast-gpt/pg/init.sql:/docker-entrypoint-initdb.d/init.sh
      - /etc/localtime:/etc/localtime:ro
  mongodb:
    image: mongo:6.0.4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /root/fast-gpt/mongo/data:/data/db
      - /root/fast-gpt/mongo/logs:/var/log/mongodb
      - /etc/localtime:/etc/localtime:ro
