mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: warning
dns:  
  enable: true  
  ipv6: false  
  nameserver:  
    - 8.8.8.8
    - 8.8.4.4 
  cache-size: 400
proxies:
    
proxy-groups:
  - { name: '♻️ 自动选择', type: url-test,  proxies: [香港V02×1.5,ABC, 印度01, 台湾03, 新加坡02, 新加坡03, 日本01, 日本02, 新加坡01,  美国01, 美国02, 台湾01, 台湾02], url: 'https://api.openai.com', interval: 3600}
rules:
  - 'DOMAIN-SUFFIX,google.com,♻️ 自动选择'
  - 'DOMAIN-SUFFIX,ai.fastgpt.run,♻️ 自动选择'
  - 'DOMAIN-SUFFIX,openai.com,♻️ 自动选择'
  - 'DOMAIN-SUFFIX,api.openai.com,♻️ 自动选择'
  - 'MATCH,DIRECT'